# HTTP Configuration
quarkus.http.port=8082

# Reactive Postgres Database Connection
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=user
quarkus.datasource.password=password
quarkus.datasource.reactive.url=postgresql://localhost:5432/analise_db

# Hibernate Reactive configuration
quarkus.hibernate-reactive.database.generation=update
quarkus.hibernate-reactive.log.sql=true

# Kafka Incoming Channel (SmallRye Messaging)
mp.messaging.incoming.proposta-criada.connector=smallrye-kafka
mp.messaging.incoming.proposta-criada.topic=proposta-criada
mp.messaging.incoming.proposta-criada.value.deserializer=io.quarkus.kafka.client.serialization.ObjectMapperDeserializer
mp.messaging.incoming.proposta-criada.value-type=br.com.caixa.habitacional.dto.PropostaCriadaEvent
kafka.bootstrap.servers=localhost:29092
