# HTTP Port
quarkus.http.port=8080

# Client REST API Configuration (External mock/provider)
# This links to the REST Client registration configKey
cliente-api/mp-rest/url=http://localhost:8084

# Redis Connection Details
quarkus.redis.hosts=redis://localhost:6379
# Enable Quarkus Cache to use Redis provider
quarkus.cache.type=redis

# Kafka Outgoing Channel (SmallRye Messaging)
mp.messaging.outgoing.propostas-enviadas.connector=smallrye-kafka
mp.messaging.outgoing.propostas-enviadas.topic=propostas-enviadas
mp.messaging.outgoing.propostas-enviadas.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer
kafka.bootstrap.servers=localhost:29092
