# ==========================================
# 1. Configuração de Rede (Servidor HTTP)
# ==========================================
# Altera a porta para evitar conflito (BindException) com o Produtor que roda na 8080
quarkus.http.port=8081

# ==========================================
# 2. Configurações de Infraestrutura Base (Kafka)
# ==========================================
# Aponta para o listener externo configurado no seu Docker Compose
kafka.bootstrap.servers=localhost:29092

# Garante fail-fast: desativa containers efêmeros caso o Docker local caia
quarkus.kafka.devservices.enabled=false

# ==========================================
# 3. Configurações de Mensageria (Recepção)
# ==========================================
# Mapeia o canal lógico "propostas-recebidas" para o driver do Kafka
mp.messaging.incoming.propostas-recebidas.connector=smallrye-kafka

# PONTO CRÍTICO: O nome físico do tópico deve ser estritamente igual ao do Produtor
mp.messaging.incoming.propostas-recebidas.topic=propostas-enviadas

# ==========================================
# 4. Desserialização e Contratos de Dados
# ==========================================
# Instrui a JVM a converter o array de bytes da rede usando Jackson
#mp.messaging.incoming.propostas-recebidas.value.deserializer=io.quarkus.kafka.client.serialization.JsonbDeserializer
# Aponta o FQN (Fully Qualified Name) da classe de destino na Heap da JVM
#mp.messaging.incoming.propostas-recebidas.value.deserializer.type=dtos.PropostaDTO

# ==========================================
# 5. Topologia do Consumer Group
# ==========================================
# Define a identidade do serviço no cluster para controle de offsets e rebalanceamento
mp.messaging.incoming.propostas-recebidas.group.id=processamento-propostas-group

# Se não houver offset comitado para este grupo, inicia a leitura desde a mensagem mais antiga
mp.messaging.incoming.propostas-recebidas.auto.offset.reset=earliest