# HTTP Port
quarkus.http.port=8084

# Datasource configuration (In-Memory H2 Database)
quarkus.datasource.db-kind=h2
quarkus.datasource.username=sa
quarkus.datasource.password=
quarkus.datasource.jdbc.url=jdbc:h2:mem:clientes_db

# Hibernate configuration to drop and recreate tables on start, and execute import.sql
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.sql-load-script=import.sql
quarkus.hibernate-orm.log.sql=true
